---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  tags:
    - update-cache

- name: Add {{ cwa_package }} key
  apt_key:
    id: "{{ cwa_package_gpg_id }}"
    state: present
    url: "{{ cwa_package_gpg }}"
  tags:
    - add-key
    - download
    - install

- name: Download {{ cwa_package }}.deb.sig file
  get_url:
    url: "{{ cwa_package_url }}"
    dest: "{{ cwa_temp_path }}/{{ cwa_package }}.deb.sig"
    timeout: "{{ cwa_global_downloads_timeout }}"
  tags:
    - download-signature
    - verify-signature
    - download
    - install

- name: Download {{ cwa_package }}.deb file
  get_url:
    url: "{{ cwa_package_url }}"
    dest: "{{ cwa_temp_path }}/{{ cwa_package }}.deb"
    timeout: "{{ cwa_global_downloads_timeout }}"
  tags:
    - download
    - verify-signature
    - install

- name: Verify {{ cwa_package }} package signature
  command: gpg --verify {{ cwa_package }}.deb.sig {{ cwa_package }}.deb
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    chdir: "{{ cwa_temp_path }}"
  tags:
    - verify-signature
    - install

- name: Install {{ cwa_package }} dependencies
  apt:
    name: "{{ cwa_dependencies_packages }}"
    state: present
    force: true
  register: package_ok
  retries: "{{ cwa_global_downloads_retries }}"
  delay: "{{ cwa_global_downloads_delay }}"
  until: package_ok is success
  tags:
    - install

- name: Install {{ cwa_package }}.deb
  apt:
    deb: "{{ cwa_temp_path }}/{{ cwa_package }}.deb"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - install
