---
# references
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-on-first-instance.html
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/verify-CloudWatch-Agent-Package-Signature.html

# debug
- name: check ansible_distribution_major_version
  debug: msg="ansible_distribution_major_version = {{ ansible_distribution_major_version }}"

- name: check ansible_distribution_release
  debug: msg="ansible_distribution_release = {{ ansible_distribution_release }}"

- name: check ansible_virtualization_type
  debug: msg="ansible_virtualization_type = {{ ansible_virtualization_type }}"

# Selective include of vars
- name: Include variables for RHEL
  include_vars: "{{ item }}"
  with_first_found:
    - "redhat.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'RedHat'
    and (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )
  tags:
    - include-redhat-vars

- name: Include variables for CentOS
  include_vars: "{{ item }}"
  with_first_found:
    - "centos.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'CentOS'
    and (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )
  tags:
    - include-centos-vars

- name: Include variables for Amazon Linux
  include_vars: "{{ item }}"
  with_first_found:
    - "amazon.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
  tags:
    - include-amazon-vars

- name: Include variables for Debian
  include_vars: "{{ item }}"
  with_first_found:
    - "debian.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'
  tags:
    - include-debian-vars

- name: Include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "ubuntu.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu'
  tags:
    - include-ubuntu-vars

# Installation tasks
- name: Include tasks for installation on RedHat/CentOS/Amazon Linux distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'Amazon'
    )
  tags:
    - include-redhat-tags

- name: Include tasks for installation on Debian/Ubuntu distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
      ansible_distribution == 'Debian' or
      ansible_distribution == 'Ubuntu'
    )
  tags:
    - include-debian-tags

# Configuration tasks
- name: Configure {{ cwa_package }}
  include_tasks: "configure.yml"
  tags:
    - configure
