---
# references
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-on-first-instance.html
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/verify-CloudWatch-Agent-Package-Signature.html

# debug
- name: debug - values from ansible facts
  debug:
    msg:
      - "ansible_os_family = {{ ansible_os_family }}"
      - "ansible_distribution = {{ ansible_distribution }}"
      - "ansible_distribution_version = {{ ansible_distribution_version }}"
      - "ansible_distribution_major_version = {{ ansible_distribution_major_version }}"
  when: show_debug_messages

# Selective include of vars
- name: include variables for RHEL - 6/7
  include_vars: "{{ item }}"
  with_first_found:
    - "redhat.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'RedHat'
    and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )

- name: include variables for CentOS - 6/7
  include_vars: "{{ item }}"
  with_first_found:
    - "centos.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'CentOS'
    and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )

- name: include variables for Amazon Linux
  include_vars: "{{ item }}"
  with_first_found:
    - "amazon.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'

- name: include variables for Debian
  include_vars: "{{ item }}"
  with_first_found:
    - "debian.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'

- name: include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "ubuntu.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu'

# debug
- name: debug - values from vars/ files
  debug:
    msg:
      - "cloudwatch_package = {{ cloudwatch_package }}"
      - "cloudwatch_package_gpg = {{ cloudwatch_package_gpg }}"
      - "cloudwatch_package_url = {{ cloudwatch_package_url }}"
      - "cloudwatch_package_signature = {{ cloudwatch_package_signature }}"
  when: show_debug_messages

# Globalize vars
- name: definning global facts
  set_fact:
    cloudwatch_package: "{{ cloudwatch_package }}"
    cloudwatch_package_gpg: "{{ cloudwatch_package_gpg }}"
    cloudwatch_package_url: "{{ cloudwatch_package_url }}"
    cloudwatch_package_signature: "{{ cloudwatch_package_signature }}"

# Installation tasks
- name: include tasks for installation on RedHat/CentOS and Amazon Linux distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'Amazon'
    )

- name: include tasks for installation on Debian/Ubuntu distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
      ansible_distribution == 'Debian' or
      ansible_distribution == 'Ubuntu'
    )
