---
# references
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-on-first-instance.html
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/verify-CloudWatch-Agent-Package-Signature.html

# Selective include of vars
- name: Include variables for RHEL - 6/7
  include_vars: "{{ item }}"
  with_first_found:
    - "redhat.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'RedHat'
    and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )
  tags:
    - include-redhat-vars

- name: Include variables for CentOS - 6/7
  include_vars: "{{ item }}"
  with_first_found:
    - "centos.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'CentOS'
    and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )
  tags:
    - include-centos-vars

- name: Include variables for Amazon Linux
  include_vars: "{{ item }}"
  with_first_found:
    - "amazon.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
  tags:
    - include-amazon-vars

- name: Include variables for Debian
  include_vars: "{{ item }}"
  with_first_found:
    - "debian.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'
  tags:
    - include-debian-vars

- name: Include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "ubuntu.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu'
  tags:
    - include-ubuntu-vars

# Globalize vars
- name: Set global facts
  set_fact:
    cloudwatch_package: "{{ cloudwatch_package }}"
    cloudwatch_package_gpg: "{{ cloudwatch_package_gpg }}"
    cloudwatch_package_url: "{{ cloudwatch_package_url }}"
    cloudwatch_package_signature: "{{ cloudwatch_package_signature }}"
  tags:
    - set-global-facts

# Installation tasks
- name: Include tasks for installation on RedHat/CentOS and Amazon Linux distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'Amazon'
    )
  tags:
    - include-redhat-tags

- name: Include tasks for installation on Debian/Ubuntu distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
      ansible_distribution == 'Debian' or
      ansible_distribution == 'Ubuntu'
    )
  tags:
    - include-debian-tags

- name: Configure {{ cloudwatch_package }}
  include_tasks: "configure.yml"
  tags:
    - configure
