---
- name: Reload {{ cwa_package }}
  command: "{{ cwa_agent_ctl }} -a fetch-config -m {{ cwa_agent_mode }} -c file:{{ cwa_agent_config_file }} -s"
  notify: Leave a copy of configuration
  when: >
    ansible_virtualization_type != "docker" or
    ansible_virtualization_type != "podman"
  tags:
    - reload

- name: Reload {{ cwa_logrotate_daemon }}
  command: "{{ cwa_logrotate_daemon }} -d {{ cwa_logrotate_config_file }}"
  when: >
    ansible_virtualization_type != "docker" or
    ansible_virtualization_type != "podman"
  tags:
    - reload

# This is necessary because after reloading the service the config file is
# eliminated, so I leave a copy to improve the idempotent and doesn't deploy
# the config file if this isn't changed
# Use configuration file from template
- name: Leave {{ cwa_package }} agent configuration file from default template
  template:
    src: agent/amazon-cloudwatch-agent.json.j2
    dest: "{{ cwa_agent_config_file }}"
    mode: 0644
    force: true
  listen: Leave a copy of configuration
  when: cwa_use_conf_json_template

# Use custom file from variable
- name: Leave {{ cwa_package }} agent custom configuration file from file content
  copy:
    content: "{{ cwa_conf_json_file_content | to_nice_json }}"
    dest: "{{ cwa_agent_config_file }}"
    mode: 0644
  listen: Leave a copy of configuration
  when: not cwa_use_conf_json_template
